name: saltstack-yubikey-formula
source: https://github.com/bechtoldt/saltstack-yubikey-formula
summary: SaltStack Formula to set up and configure tools for YubiKey, a hardware solution for two factor and OTP authentication
todo:
  - add instructions how to use formhelper, add information about it in the formula-docs (dependency), show up alternative?
  - 'table/ matrix: os/salt compatibility (dedicated file)'
  - add list of available states
  - add tests
